#!/bin/bash

read line
alt="$(echo "$line" | sed -e 's/^!\[\(.*\)\].*/\1/')"
url="$(echo "$line" | sed -e 's/^.*(\(.*\))/\1/' -e 's/\?.*//')"

cat <<EOF
<div align="center">
<img
src="$url"
alt="$alt">
<br>
<i><small>
caption
</small></i>
</div>
<br>

EOF
